# Generated by Django 4.2.7 on 2023-12-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sp_department',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
