# Generated by Django 4.2.7 on 2023-12-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_id', models.IntegerField()),
                ('farmer_id', models.IntegerField()),
                ('senderid', models.IntegerField()),
                ('recid', models.IntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
